### ISSUE TITLE
Camera enters in objects

### ISSUE THREAD

**Issue by PaulMarisOUMary** [algosup/2022-2023-project-4-game-design-Team-5#6]
### **Describe the bug**
The camera enters the objects which obstructs the view and can disturb the user experience.

### **To Reproduce**
1. Launch the app
2. Move using `Z` `Q` `S` `D`
3. Move the player towards a large object
4. Observe how the camera enters the object, obstructing the view

### Area
UX

### **Expected behavior**
The camera should stop, move around or anything more user-friendly before entering the object and allow the user to see without obstruction.

### **Actual behavior** and **Screenshots**

https://user-images.githubusercontent.com/71769515/230569334-806a0439-096e-473e-9a43-ff4fa8e35d9b.mov

### **Environment**
- MacOS Ventura version 13.3; arm (Apple M1)

**Comment by Guillaume-Riviere** [comment]
This Issue should be corrected with the new update, 
You should see through object now

**Comment by PaulMarisOUMary** [comment]
Thanks, see #10
