### ISSUE TITLE
Sphere with collision appears randomly on levels

### ISSUE THREAD

**Issue by PaulMarisOUMary** [algosup/2022-2023-project-4-game-design-Team-5#9]
### **Describe the bug**
A ball appears in the level at a random location in the map, and this ball has collisions enabled, not allowing the player to move through it.

### **To Reproduce**
1. Launch the game.
2. Start playing in any level.
3. Wait for a ball to appear randomly on the level.
4. Try to move your character through the ball.

### **Area**
Gameplay, Physics

### **Expected behavior**
The ball should not appear and the player should be able to move through it.

### **Actual behavior**
The ball shows up and has collision enabled, the player is not able to move through it.

### **Screenshots**
https://user-images.githubusercontent.com/71769515/231086105-315cb30c-2d70-4c88-84ba-59f480e528ac.mp4

### **Environment**
- Operating System `MacOS Monterey version 13.3; arm (apple M1)`
- Unreal version 4.27

### **Additional context**
This bug occurs randomly and has been observed on each levels.

**Comment by Guillaume-Riviere** [comment]
It appears in the editor when it's launched directly in the editor
It's because there is no game actor in the editor ( It comes from the Menu )
